# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship(1)(c0a81cd4-e4ff-4f6a-a613-0d70aced5676)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo "Authorizing Azure Login ..."'

- script: |
     sudo apt update
     sudo apt install -y ansible

- script: |
    cd Day5/TerraformWithAnsible
    terraform init
  displayName: 'Initialize Terrform Project'

- script: |
    cd Day5/TerraformWithAnsible
    terraform apply --auto-approve
  displayName: 'Provision 3 VMs and Install Nginx Web Server'
